# Generated by Django 3.0.4 on 2020-03-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='next',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stop',
            name='prev',
            field=models.CharField(max_length=30),
        ),
    ]
