# Generated by Django 3.0.4 on 2020-03-12 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_auto_20200313_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstopreal',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='busstopreal',
            name='stop',
        ),
        migrations.AddField(
            model_name='busstop',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.Route'),
        ),
        migrations.AddField(
            model_name='busstopreal',
            name='busstop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.BusStop'),
        ),
    ]
