# Generated by Django 3.0.4 on 2020-03-15 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_auto_20200313_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.TimeField()),
                ('departure', models.TimeField()),
                ('status', models.CharField(default='NOT STARTED FROM TERMINAL', max_length=50)),
                ('busstop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.BusStop')),
            ],
        ),
    ]
