# Generated by Django 3.0.4 on 2020-03-22 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_busschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='busschedule',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bus.Route'),
        ),
    ]
