# Generated by Django 3.0.4 on 2020-03-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_busschedule_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busschedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Route'),
        ),
    ]
