# Generated by Django 3.0.4 on 2020-04-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_city_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='state',
        ),
    ]
